### ISSUE TITLE
Implementations page is inconsistent

### ISSUE THREAD

**Issue by ulope** [libp2p/website#102]
The implementations page is inconsistent in the implementations listed.

All categories have 
- `Browser JS`
- `Node JS`
- `Go`

All except for `NAT Traversal` and `Discovery` also include
- `Rust`

`Record Stores` additionally has
- `C#`

This seems quite confusing to me.
All implementations should be listed for all categories.

Also the Python and Java implementations are missing entirely.

**Comment by DannyS03** [comment]
Now being addressed in https://github.com/libp2p/website/issues/138
