### ISSUE TITLE
Going live with libp2p.io (split into smaller issues)

### ISSUE THREAD

**Issue by VictorBjelkholm** [libp2p/website#12]
So, let's kick in the high gear and go live with a iteration of the website that we can show people and make use of. Then we can figure out a more proper design, have some more content like demos and such.

But first things first! What we're missing for the first iteration, described with the site structure we want:
- [ ] Landing Page
  - [ ] Small visual demo, showing off libp2p with connecting nodes
  - [ ] Features
  - [ ] Languages supported: Go, JS + others coming (logos of the languages kind blurred out)
  - [ ] Talks & Conferences
  - [ ] Contribute & Community
- [ ] Implementations Page
  - [ ] Generic table that can be reused for all the different sections. Has
    the module name on the y axis and language on the x axis. Top of the table
    includes links to the interface. Color of the cell is either red, yellow or
    green depending on implementation status
  - [ ] Sections
    - [ ] transport
    - [ ] stream-muxer
    - [ ] discovery
    - [ ] connection-upgrades (we don't have any of these yet)
    - [ ] crypto channel
    - [ ] discovery
    - [ ] peer-routing
    - [ ] record-store
- [ ] Bundles < Prepackaged libraries with set of features < description of what bundles
  - [ ] libp2p-browser
  - [ ] libp2p-node
  - [ ] go-libp2p
- [ ] Examples (code snippets)
  - [ ] Quickstart < Connection to other peers, basically the same as the landing page demo
  - [ ] Establishing encrypted connection
  - [ ] Handling multiple protocols in the same connection (multiplex connection)
  - [ ] Discovery local + remote peers
- [ ] Link to specification on Github

Sounds good?

**Comment by diasdavid** [comment]
@VictorBjelkholm also added this repo to the JavaScript team of libp2p and added you to the team, so that you can commit directly to the branches

**Comment by VictorBjelkholm** [comment]
Inspiration for website:
* http://leveldb.org/
* http://iswebrtcreadyyet.com/
* http://webtorrent.io/
* http://socket.io/demos/chat/
* https://github.com/d3/d3/wiki/Gallery

**Comment by VictorBjelkholm** [comment]
Sketches from todays call that we agreed on:

![photo_2016-12-14_14-23-59](https://cloud.githubusercontent.com/assets/459764/21183618/0df5cdee-c209-11e6-865f-147d84cb52f3.jpg)
![photo_2016-12-14_14-24-01](https://cloud.githubusercontent.com/assets/459764/21183616/0df5a940-c209-11e6-963f-6ab13c78b562.jpg)

/cc @jbenet @diasdavid

**Comment by VictorBjelkholm** [comment]
Closing this in favor of the other issues, now in Milestone https://github.com/libp2p/website/milestone/1
