### ISSUE TITLE
(possibly) unclear formulation in protocols concept page

### ISSUE THREAD

**Issue by GGAlanSmithee** [libp2p/website#127]
In the protocols concept page of the website, under the [binary streams section](https://docs.libp2p.io/concepts/protocols/#binary-streams) it states that:

> Behind the scenes, libp2p will also ensure that the stream is secure and efficiently multiplexed. This is transparent to the protocol handler, which reads and writes unencrypted binary data over the stream.

I am not a native english speaker so please excuse any missinterpretations, but if the underlying implementation (which in this context is that the stream is encrypted and multiplexed) is **transparent** to the protcol handler, isn't the statement "which reads and writes unencrypted binary data over the stream" contradictory? Is it not, in fact, by that definition opaque to the handler?

This is of course not a major thing, but I want to understand things correctly, so can someone please clarify the intended meaning and if it is indeed worded wrong, I can submit a PR to change it.

Thanks

**Comment by mxinden** [comment]
Thanks for opening the issue @GGAlanSmithee. I see how this can be confusing. Would something along the lines of the following be more intuitive?

> Behind the scenes, libp2p will also ensure that the stream is secure and efficiently multiplexed. This is transparent to the protocol handler. The protocols handler writes and reads unencrypted data to/from the stream. libp2p takes care of then en- and decrypting those bytes before / after being send on the wire.

A pull request would be very much appreciated. Thanks @GGAlanSmithee.

**Comment by GGAlanSmithee** [comment]
@mxinden 

My pleasure!

I actually think the original text is clear enough.

I got hang up on the word _**transparent**_. To me, that means you can see through something, ie. exposing details through an abstraction, whereas the statement following that kind of contradicted it by stating that those details are mroe or less **not** visible to the handlers.

I think the problem here is my inability to understand the text and not a general problem. :) Thanks a lot for your time and reply, I will see if there is something more valuble I can contribute with, because again, I think the error is on my side and that the original text is clear enough.
