### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by VictorBjelkholm** [libp2p/website#13]
Landing page is the most important part of the website, to allow people to understand quickly what libp2p is about and how they can use it.

Currently planned to include:

- [ ] Small visual demo, showing off libp2p with connecting nodes
- [ ] Features
- [ ] Languages supported: Go, JS + others coming (logos of the languages kind blurred out)
- [ ] Talks & Conferences
- [ ] Contribute & Community
- [ ] Link to specification on Github in header
- [ ] Link to Github entry-repo in header

**Small Visual Demo**
We'd love to have a visual experience above the fold of the website, showing how you as a visitor is instantly connected to other nodes. 

**Content needed from @diasdavid**
- [ ] Opening paragraph that we can list above the fold as well
- [ ] Which features to list? Title + Description
- [ ] Which videos/talks to list on landing page

For the Contribute & Community section, maybe we can reuse the one from IPLD written by @RichardLitt ?

> IPLD is an open source project from the IPFS community. There are many ways you can contribute by getting involved: you can help write the specification, code implementations and tools using IPLD, craft examples and tutorials, and join our regular product calls to discuss IPLD with us.

**Comment by RichardLitt** [comment]
Reusing sounds fine to me.

**Comment by VictorBjelkholm** [comment]
From David

> @VictorBjelkholm couldn't find the issue where you requested this, but here it goes:
> 
> ### Opening line
> 	A modular network stack, run your network applications free from runtime and address services independently of their location.
> 
> ### Features to highlight
> 
> 	Use several transports
> Your application can use newer and more performant transports like QUIC, WebRTC while still providing TCP without having to change the way it works.
> 
> 	Location independent
> With libp2p, addressing is made per process which means that independently of where the process is running, you will be able to dial to it
> 
> 	Runtime freedom
> The libp2p interface is independent of the runtime, your app can run natively or in the browser without requiring to change how it handles the network stack
> 
> 	Protocol Muxing
> Reuse existing pipes to mux between protocols, reducing the delay caused by things like TCP slow start and hole punching (the same benefit present in HTTP/2).
> 
> 	Work offline
> libp2p is capable of discovery other peers without resourcing to centralised registries, enabling apps to work disconnected from the backbone
> 
> 	Encrypted connections
> Ensure that every connection that is made is using an encrypted channel by picking one of the available options.
> 
> 	Upgrade without compromises
> Libp2p protocol muxing enables your application to support several versions of its networked services, enabling you to have a smooth migration over time
> 
> 	Work in the browser
> With libp2p, you can dial out from a browser session but also dial in! Other peers in the network have the ability to route packets to the browser.
> 
> 	Good for high latency scenarios
> Using a packet switching routing (soon), libp2p can make your application work in networks where other transports would simply fail.
> 
> ### Projects using libp2p
> - IPFS
> 
> ### Videos + Talks
> 
> See the talks section : https://github.com/libp2p/js-libp2p#background
> 
> ### Bundles
> 
> You can find some copy at: https://github.com/libp2p/js-libp2p#bundles
> 
> ### More Juicy content
> - https://github.com/libp2p/js-libp2p#background

**Comment by VictorBjelkholm** [comment]
Made a preliminary build that is visible over here:  https://ipfs.io/ipfs/QmNqHsJNqt2ApsrbQnRqswL51yycdecTFkp4WzDNuiTGW5/

Full page:

![](https://pageshot.net/images/7ed86b89-8cac-4999-ac45-4d4d7509ef8d.png)

Added new todo items in the top

**Comment by diasdavid** [comment]
Well, I'm sure you have improvements on the design in mind (starting from the vibrant colors :D), but here goes some feedback:

- `s/Supported Languages/Implementations in/` and then list the 3 builds we have, saying that we have browser and Node.js communicates a lot of value
- I don't understand with the nav bar has items all over, shouldn't they be next to each other?
- Needs bigger fonts
- s/Talks & Conferences/Publications and Talks/g
- s/Contribute & Community/Community/g - Invite people to follow @IPFSbot and @libp2p (account is suspended, already sent request to twitter), to join our #IPFS channel in freenode and to join our libp2p hangouts.
- I would do 2 columns instead of 3 for the Highlights
- It would be sweet if the graph showed more information, such as: transport, IP
- It would be sweet if instead of dots, the nodes were hexagons 

Also, it might be a very good idea to have the libp2p hangouts listed, just not in the main page, thougts?

**Comment by jbenet** [comment]
Came here to add:

> for the graph, maybe the nodes should be the flag of the country the ip addr is in.

---

- the official name mark is "libp2p". not "LibP2P". the name comes from unix libraries, which are all lowercase. If you would like to propose changing the name, we should discuss it separately.
- I dislike the vibrant colors, but can we get all the _content_ in place before hashing out the design? I think we will get stuck arguing about what different people like. It may be best to hand this to a designer or use one of the several (professional designer) designs we have lying around.
- Could any of the unused PL website designs work for libp2p?  -- maybe worth discussing together with @jesseclay

**Comment by VictorBjelkholm** [comment]
@diasdavid @jbenet  thanks a lot for the feedback!

> I don't understand with the nav bar has items all over, shouldn't they be next to each other?

Yeah, might be better to position the github + spec links under the nav on the right. Idea is that the external links (github and spec) are different from the internal links (navigation links)

> s/Contribute & Community/Community/g - Invite people to follow @IPFSbot and @libp2p (account is suspended, already sent request to twitter), to join our #IPFS channel in freenode and to join our libp2p hangouts.

We should get @RichardLitt to modify the existing one, and possibly apply the changes to IPLD as well.

> It would be sweet if the graph showed more information, such as: transport, IP

Hm, my fear is that it'll become to cluttered with too much text flying around. Probably we gonna have to limit to number of nodes showing anyways, but it's almost already to cluttered. I like the idea of showing the country flag of where the node is though, and hide the ID.

> the official name mark is "libp2p". not "LibP2P". the name comes from unix libraries, which are all lowercase. If you would like to propose changing the name, we should discuss it separately.

I'm trying to find where it says "LibP2P" rather than "libp2p", but I can't find it. I agree it should be libp2p.

> I dislike the vibrant colors, but can we get all the content in place before hashing out the design?

Agree, colors are temporary to just separate the sections. I would also prefer more content before nailing down the design.

And would prefer even more to have a professional design instead, if we have that resource available.

**Comment by VictorBjelkholm** [comment]
Address most of the comments made here: (live version: https://ipfs.io/ipfs/QmaKrk1P5jDasywLA7KZ2MTwadzK3dDAXgeXnTweYGBGAM/)

![](https://pageshot.net/images/55e654b1-01bb-496f-b02e-97e2dcf576af.png)
