### ISSUE TITLE
Bundles page

### ISSUE THREAD

**Issue by VictorBjelkholm** [libp2p/website#15]
This page is for listing the bundles, already made configurations for simple usage.

- [x] Bundles < Prepackaged libraries with set of features < description of what bundles
  - [x] libp2p-browser
  - [x] libp2p-node
  - [x] go-libp2p

**Comment by VictorBjelkholm** [comment]
@diasdavid made a version here, thoughts?

![](https://pageshot.net/images/ba36ff69-e19c-4412-b9cd-0430e7918425.png)

**Comment by diasdavid** [comment]
Niiiice :)

Some feedback:

Seems that the names of the cards break out of the card if the browser is resized
![image](https://cloud.githubusercontent.com/assets/1211152/21415667/5a34256a-c804-11e6-82a7-2b4eca35f282.png)

The libp2p at the top is a different font and color scheme from the one available.

Should the license at the bottom be "All rights reserved" or `© Protocol Labs | Except as noted, content licensed CC-BY 3.0.` like in ipfs.io?

It would be great to list out the features that each bundle currently has.

It would also be very helpful if the bundles suggest some place where people that visit the webpage can get a 'getting started' with that bundle.
