### ISSUE TITLE
"More Videos" button cutoff 

### ISSUE THREAD

**Issue by p-shahi** [libp2p/website#153]
A tiny bug on the libp2p home page where the "More Videos" button is cutoff.
![image](https://user-images.githubusercontent.com/50885601/197584535-b523f6b1-5242-44e9-83d2-b8333ba7f4d3.png)

**Comment by DannyS03** [comment]
Still an issue?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/25497083/209062642-9d048f52-c82f-4be4-b841-81fff1d7ae45.png">
