### ISSUE TITLE
Examples page

### ISSUE THREAD

**Issue by VictorBjelkholm** [libp2p/website#16]
A separate page for examples and demos. Would be great if could somehow load these demos from SCM or some external page, so the code itself doesn't live in the website.

We have a lot ideas of different kinds of demos we can do. Here is some of them:

  - [ ] Establishing encrypted connection
  - [ ] Handling multiple protocols in the same connection (multiplex connection)
  - [ ] Discovery local + remote peers

What we definitely want to have on this page:
- [ ] Basic example - could basically be the same as the one on the landing page, but showing the code for it as well
- [ ] Chat - Enables you to chat with the rest of the people that is visiting the same page as you

**Comment by jesseclay** [comment]
@VictorBjelkholm @diasdavid ping on this page -- do either of you have ideas on how this page should look? I'm working with designers now to make the site happen & this is currently an empty tab on the website. I assume I should make this page & leave areas for the examples to be put into, yeah?

**Comment by jesseclay** [comment]
ah nvm that was dumb -- see now you explained things in the content issue. 

Though I guess this can serve as a ping to get the examples done? Just do them with all your spare time! (hah)
