### ISSUE TITLE
Content requested

### ISSUE THREAD

**Issue by diasdavid** [libp2p/website#17]
@VictorBjelkholm couldn't find the issue where you requested this, but here it goes:

### Opening line
	A modular network stack, run your network applications free from runtime and address services independently of their location.

### Features to highlight

	Use several transports
Your application can use newer and more performant transports like QUIC, WebRTC while still providing TCP without having to change the way it works.

	Location independent
With libp2p, addressing is made per process which means that independently of where the process is running, you will be able to dial to it

	Runtime freedom
The libp2p interface is independent of the runtime, your app can run natively or in the browser without requiring to change how it handles the network stack

	Protocol Muxing
Reuse existing pipes to mux between protocols, reducing the delay caused by things like TCP slow start and hole punching (the same benefit present in HTTP/2).

	Work offline
libp2p is capable of discovery other peers without resourcing to centralised registries, enabling apps to work disconnected from the backbone

	Encrypted connections
Ensure that every connection that is made is using an encrypted channel by picking one of the available options.

	Upgrade without compromises
Libp2p protocol muxing enables your application to support several versions of its networked services, enabling you to have a smooth migration over time

	Work in the browser
With libp2p, you can dial out from a browser session but also dial in! Other peers in the network have the ability to route packets to the browser.

	Good for high latency scenarios
Using a packet switching routing (soon), libp2p can make your application work in networks where other transports would simply fail.

### Projects using libp2p
- IPFS

### Videos + Talks

See the talks section : https://github.com/libp2p/js-libp2p#background

### Bundles

You can find some copy at: https://github.com/libp2p/js-libp2p#bundles

### More Juicy content
- https://github.com/libp2p/js-libp2p#background

**Comment by VictorBjelkholm** [comment]
Many thanks! Copied it over here: https://github.com/libp2p/website/issues/13
