### ISSUE TITLE
Content for the Website

### ISSUE THREAD

**Issue by diasdavid** [libp2p/website#18]
Heey Jesseeee, here is what you askes. With ❤️ @diasdavid and @VictorBjelkholm 

@jesseclay
-----------------------

# libp2p website

## Sitemap

```
|- /        - Landing Page
|- /modules - Implementations (Modules)
|- /bundles - Bundles
`- /specs   - Examples (Demos)
```

## Navigation

Every page should contain the same navigation bar, containing links to the subpages of the libp2p website and other places of relevant information for libp2p interested users.

The navigation bar should float with the user as they uncover the website, having the extra task of offering the users a way to get back to the beginning.

List of items in the navigation:
- modules - /modules
- bundles - /bundles
- examples - /examples
- Github (external) - https://github.com/libp2p/libp2p
- Specification (external) - https://github.com/libp2p/specs

### Landing Page

**Above the fold**
- Title: `libp2p logo`
- Tagline: `A modular network stack, run your network applications free from runtime and address services independently of their location`
- Embedded Demo - Visual representation of several nodes (peers/machines) connected together. These machines will be the actual visitors of the website. A JavaScript example of how to achieve this can be found at: https://github.com/VictorBjelkholm/libp2p-demo.

**Below the fold**

- Features. List of features found at: https://github.com/libp2p/website/blob/668814879ddae644d976d51f6c2c08cd715ae515/config.yml#L25-L43

- Bundles listing: These are the bundles available in different Runtimes.
  - `Browser`
    - url: https://github.com/ipfs/js-libp2p-ipfs-browser
    - list the modules that are inside: spdy, webrtc-star, websockets, secio, identify
  - `Node.js `
    - https://github.com/ipfs/js-libp2p-ipfs-nodejs
    - list the modules that are inside: spdy, webrtc-star, websockets, secio, identify, mdns
  - `Go `
    - url: https://github.com/libp2p/go-libp2p
    - list the modules that are inside: spdy, yamux, tcp, utp, websockets, secio, identify, mdns, dht, relay, railing
  - `"Create your own custom bundle"` - Link to page with instructions to build a js bundle and suggesting that it can be done in other languages with the other language pieces  github.com/libp2p/libp2p#custom-bundle - needs to be created)
- Publications & Talks: 
  - Tutorials
    - video walkthrough made by David (coming soon™)
  - Papers
    - "COMING SOON"
    - [Specification (WIP)](github.com/libp2p/specs)
  - Talks
    - [DATE][EVENT][TITLE][SPEAKER]
    - DEVCON2 libp2p talk https://www.youtube.com/watch?v=HxueJbeMVG4
    - Panel at the Decentralised Web Summit https://archive.org/details/DWebSummit2016_Panel_Peer_to_Peer_Networks
- Community
  - invitive paragraph to the community
  - link to IRC #ipfs on freenode
  - link to community page in github.com/libp2p/community
  - link to twitter twitter.com/libp2p
- Footer
  - Same info as ipfs.io
  - replace the ipfs twitter and github by twitter.com/libp2p and github.com/libp2p respectively

### Implementations Page

The implementations page should contain several tables, each table will be dedicated to one of the type of modules, the tables should represent the state of each module. One great source of inspiration is: http://iswebrtcreadyyet.com/

Table example

# Stream Multiplexer

- [**interface-stream-muxer**](github.com/libp2p/interface-stream-muxer)

name | JavaScript | Go | Rust
-----|------------|----|-----
libp2p-spdy | <state> | <state> | <state>
libp2p-yamux | <state> | <state> | <state>
libp2p-multiplex | <state> | <state> | <state>

Possible states:
- Missing
- Prototype (Unstable, might catch fire)
- In progress (Usable)
- Done

See https://github.com/libp2p/website/issues/14 for more info.

- List of tables: https://github.com/libp2p/website/blob/17b328827ae61c21a5cbd6d104e2114d3d6f29c1/data/modules.yml

### Bundles Page

This page should included the bundles and their features listed above, but expanded with pointers to examples and how to get started with them.

More info at: https://github.com/libp2p/website/issues/15

### Examples Page

We have several examples prepared for libp2p, what we are looking for to have ready for this page is a way to present several examples in one page and a way to easily add more to these gallry

In the gallery, there should be a visual queue of what the example list and a table of contents of the examples available. Take inspiration from D3JS page, here: https://github.com/d3/d3/wiki/Gallery

Each example will have instructions to use it and some visual diagrams of what it is doing.

## Inspirations

- Take a lot from http://leveldb.org/
- Inspiration for the implementations page http://iswebrtcreadyyet.com/
- Inspiration for the Examples 
- https://github.com/d3/d3/wiki/Gallery

**Comment by diasdavid** [comment]
@jesseclay for the features:

#### "Use several transports"

This one really needs to bring up words like TCP, UTP, WebRTC and HTTP/2

#### "Location independent"

Let's update the text on this one to 'Native Roaming' and the illustration can be like: http://www.trutower.com/wp-content/uploads/2013/05/Connected-World-1-620x412.jpg

#### "Runtime freedom"

Needs to show more runtimes
- Browser
- Desktop
- Mobile
- IoT

All connected

#### "Protocol Muxing"

Like this https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Multiplexing_diagram.svg/250px-Multiplexing_diagram.svg.png but better and with each arrow being a different protocol a la multicodec ("/bitswap/1.0.0")

#### "Work offline"

Show two networks, one being the global and another one being disconnected from the global. Both of them have connectivity within their own area

#### "Encrypted connections"

What about the idea of 'armoring the wire' or putting barbed wire to protect the communications?

#### "Upgrade without compromises"

We had talked about a notification bubble, any thoughts on why that didn't pass through.

#### "Work in the browser"

It's good, but what about putting also logos of the major browsers, can we do that?

#### "Good for high latency scenarios"

Can the image be of a remote area? A shack in a mountain? A boat?

**Comment by jesseclay** [comment]
@diasdavid need a description for each of the cards -- wanna take a quick stab at it?

![image](https://cloud.githubusercontent.com/assets/1719763/24027124/782860a2-0a82-11e7-9306-a7220ab75fb5.png)

**Comment by diasdavid** [comment]
You can find my previous descriptions here -- https://github.com/libp2p/website/issues/17#issue-196258906 --but here is an update.

- `Use several transports` - Use newer and faster transports like QUIC and WebRTC at the same time you support more well-established ones such as TCP, supporting multiple hosts and connectivity conditions.
- `Location independent` - You get **Native Roaming** out of the box, your app or service can be migrated between machines or move between networks without any configuration steps.
- `Runtime Freedom` - You can just assume you get connectivity, independently of the platform you are running your software on.
- `Protocol Muxing` - Avoid unnecessary extra connection setups by reusing already established and secure connections with in-band protocol multiplexing.
- `Work offline` - _You already have this one_
- `Encrypted connections` - Ensure that no one can eavesdrop on yours users traffic by setting a crypto channel by default, this way both bits are protected and identities of the peers are validated.
- `Upgrade without compromises` - Don't lock your application into a decision you made in the past, with wire protocol versioning, you can upgrade your service and support older versions without complicated setups.
- `Work in the browser` - Yes, you can use the browser as your platform to create fully P2P services.
- `Good for high latency scenarios` - Make your app smarter by understanding network conditions and picking better options when it comes to dial to other peers.

**Comment by jesseclay** [comment]
all content implemented in the latest site! Thanks for this.
