### ISSUE TITLE
Icons for Features

### ISSUE THREAD

**Issue by jesseclay** [libp2p/website#19]
Here are currently proposed icons for the "features" section of the website:

![image](https://cloud.githubusercontent.com/assets/1719763/22677114/16801368-eca5-11e6-9abf-2da443b76eb5.png)

Some of these do a good job, others not so much. Feedback? What do you like here, what needs to be different?

(note that the description of the feature appears on mouseover.

**Comment by VictorBjelkholm** [comment]
"Use Several Transports" > Kind of lazy one, just a bunch of the different transports rather than something explain transports.

"Works in the browser" > Not sure why the icons look kind of like the browser icons, but not really. Would be better to just use the browser icons directly + the Firefox icon seems to be missing, unless that's the "Obama"-one in the middle. Don't think it's clear enough.

The other ones we can see I think look good. The icon for "Work Offline" is missing though.

**Comment by jbenet** [comment]
- Use the actual logos from the browser.

**Comment by jbenet** [comment]
My feedback in image form

![image](https://cloud.githubusercontent.com/assets/138401/22708269/80558d6a-ed2a-11e6-9684-ff8d1ebdb95c.png)

**Comment by jesseclay** [comment]
how about this direction & style @jbenet @diasdavid @VictorBjelkholm 

![](https://cloud.githubusercontent.com/assets/5362850/22753937/235f4096-ee3e-11e6-955d-98f3442a919b.png)

**Comment by diasdavid** [comment]
Can we switch 'Location Independent' to 'Native Roaming?
I like more https://github.com/libp2p/website/issues/19#issuecomment-278117335 than https://github.com/libp2p/website/issues/19#issuecomment-278442969

**Comment by dignifiedquire** [comment]
> Native Roaming

I don't think a lot of people will understand what that means (at least I wouldn't)

**Comment by diasdavid** [comment]
It is a networks term, means you can move between locations without having everything break loose (gracious handoff)

**Comment by jesseclay** [comment]
update. Get @ me with thoughts. I didn't provide carefully considered sketches for this (fail), so designers are kind of shooting in the dark:

Design A
![](https://cloud.githubusercontent.com/assets/22168118/22831531/f9ae219a-efaa-11e6-948a-30deb543bc9c.png)

Design B
![](https://cloud.githubusercontent.com/assets/5362850/22834991/700fa03c-efb7-11e6-8eff-53c687e373f4.png)

Design C
![](https://cloud.githubusercontent.com/assets/5362850/22834992/7010c7be-efb7-11e6-986a-d69d2ec4666c.png)
