### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by masylum** [libp2p/website#2]
Having this online can make a huge difference on how people contribute to IPFS. I often myself navigating across dozens of repos trying to make sense to the whole picture. I think having a home for libp2p with links to the implementations, specs and documentation would really ignite contributions.

Same for merkledag and bitswap. By splitting the cognitive barrier into smaller pieces people are more willing to contribute.

Let me know if you are interested on me helping on that front.

**Comment by masylum** [comment]
(Also the logo can receive some love too :smile:)

**Comment by diasdavid** [comment]
Hi @masylum for sure would love your help! Right now we have a bunch of issues open at https://github.com/ipfs/js-ipfs/issues referring to repos where we need more help in the JS world.

As for announcing it, we made a decision (during the sprint calls) of doing that properly once we get the Go version ready and interoping with the JS version. We will make proper use cases for it, examples, tutorials and videos.

**Comment by Mec-iS** [comment]
Also a weekly newsletter posting the status updates would be useful for the purpose. Developers may have been missing updates among the different  repositories, or maybe a simple forum or a trello-like dashboard for the teams to post notes and references to Issues. This messages posted could be piped into a newletter to be ready for fast reading and newspicking.

**Comment by zjiekai** [comment]
Is this repo abandoned?

**Comment by diasdavid** [comment]
We haven't pushed for the website, but the project is really active :)

**Comment by RichardLitt** [comment]
I'm guessing I am supposed to overhaul libp2p.io, right, @diasdavid?

**Comment by RichardLitt** [comment]
Yes, this is the case, past @RichardLitt.

**Comment by VictorBjelkholm** [comment]
Closing this in favor of https://github.com/libp2p/website/issues/12 where we have a list of things missing
