### ISSUE TITLE
d3 Map Animation for home page

### ISSUE THREAD

**Issue by jesseclay** [libp2p/website#20]
I had our designers create all the assets we should need to make a SICK map visualization for the homepage. Basically we want to take this:

https://ipfs.io/ipfs/QmZCkufaASVc8pn4XQRDQA1xi6t3Lv7rmEoZUMukXRo8ko/

and turn it into this:

![image](https://cloud.githubusercontent.com/assets/1719763/22721683/1c928462-ed67-11e6-952d-dbb015958782.png)

I've included the map image, in addition to the svg files for the colored lines & hexes. The box with location info is not included, it's assumed that would be made with CSS (could be a d3 element too, maybe that makes more sense). Make the location box the same color as the hex, & randomize the colors of placed hexes. Lines should match the color of the hex it's leaving. Just match the image &  ok yes I'll shut-up now.

This should be fun, who wants it @VictorBjelkholm @diasdavid??

[Maps](https://www.dropbox.com/sh/vat3xk21cnj9ttj/AACFlw0ZqDNSfcI7o5jXpoIia?dl=0) (both grey & white included, I think we'll end up using white)
[Hexes & lines](https://www.dropbox.com/sh/ftyhxwgrihpnv4x/AAB3G-z-jyaQBx2uKXDkE-N6a?dl=0)

**Comment by Kubuxu** [comment]
This means using geoip mappings that we did in the past, can we reuse parts of it?

**Comment by dignifiedquire** [comment]
our current geoip datasets are not that great

the module is at https://github.com/ipfs/ipfs-geoip

**Comment by VictorBjelkholm** [comment]
Maybe it would simpler to when the user scrolls down to the page where they can see the example, we ask for location information from the browser. Then instead of the map, we show a message on top of the map of why we want to have the location, and the user can decline/approve.

It very much would be fun to implement, but not sure I currently have the time to do it, with my other commitments.

**Comment by jesseclay** [comment]
don't worry everyone, I spent all last night and finished this. Here it is: [https://github.com/jesseclay/libp2p-d3-map](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by jesseclay** [comment]
@jbenet @diasdavid where are we with this? Sounds like many hours of work away so best to ship site w/o this + examples page for now, then add in later?

**Comment by DannyS03** [comment]
Can revisit a similar addition with a design update for the site, and redefine the feature. Please reopen if otherwise
