### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by lgierth** [libp2p/website#21]
```
> hugo version
Hugo Static Site Generator v0.19 linux/amd64 BuildDate: 2017-02-27T13:35:55+01:00
> hugo
Started building sites ...
Error: Error building site: Failed to read data from icons/c.svg/c.svg: Data not supported for extension 'svg'

```

**Comment by VictorBjelkholm** [comment]
Tried building with 0.18 first and everything worked fine. Upgraded to hugo 0.19 and now things are broken. But, we're not even using the svgs anymore, so removed them and now it builds fine with 0.19 as well. Try pulling latest from master and things should work.

Anyways, I don't think this is the current version that we want to be deploying.

**Comment by diasdavid** [comment]
should be good now, @jesseclay just pushed the new version.
