### ISSUE TITLE
Add section for articles on the Media page

### ISSUE THREAD

**Issue by diasdavid** [libp2p/website#25]
Some links for it:

- http://icwe2016.inf.usi.ch/program/tutorials/ipfs
- http://dapps.hatenablog.com/entry/2016/10/30/000000
- devcon talk slides https://ethereumfoundation.org/devcon2/wp-content/uploads/2016/10/libp2p-HEART-devp2p-IPFS-PLUS-Ethereum-networking.pdf

**Comment by alanshaw** [comment]
That third link is 404ing.

Any of these? https://ethereumfoundation.org/devcon2/wp-content/uploads/2016/10/

Damn that non-permanent web.

**Comment by diasdavid** [comment]
Uploading it here:

[devcon2.pdf](https://github.com/libp2p/website/files/1196932/devcon2.pdf)

> Damn that non-permanent web. 

I know..!

**Comment by alanshaw** [comment]
Thanks, #58 is updated
