### ISSUE TITLE
Not all tables must have a interface url

### ISSUE THREAD

**Issue by diasdavid** [libp2p/website#26]
Namely:

![image](https://cloud.githubusercontent.com/assets/1211152/24594805/b01e3f16-17fe-11e7-9bd6-3c00a83617d5.png)

![image](https://cloud.githubusercontent.com/assets/1211152/24594808/b4fee9d6-17fe-11e7-83bf-5980275240bf.png)

![image](https://cloud.githubusercontent.com/assets/1211152/24594810/ba3332b8-17fe-11e7-9f31-1ec64904e077.png)

![image](https://cloud.githubusercontent.com/assets/1211152/24594813/bebe108c-17fe-11e7-90a3-c62f62563b45.png)

![image](https://cloud.githubusercontent.com/assets/1211152/24594816/c921c58c-17fe-11e7-8bd0-787881aff836.png)

![image](https://cloud.githubusercontent.com/assets/1211152/24594819/ce7e5a7c-17fe-11e7-93d9-c10ffff8a16d.png)

**Comment by jesseclay** [comment]
done in #41
