### ISSUE TITLE
make more pleasing footer

### ISSUE THREAD

**Issue by jesseclay** [libp2p/website#32]
Even though I implemented the current footer, I think it looks weird... it's not up to the quality of the rest of the website:

![image](https://cloud.githubusercontent.com/assets/1719763/24595445/a969b8de-1804-11e7-91ef-c0c7f2e28089.png)

I'd like to see a better version of this.

**Comment by jesseclay** [comment]
Some footer options:

A
![homepage - footer - option 1](https://cloud.githubusercontent.com/assets/1719763/24758412/4709885a-1ab0-11e7-8fb4-0f542f5d9b57.png)

B
![homepage - footer - option 2](https://cloud.githubusercontent.com/assets/1719763/24758413/471cc23a-1ab0-11e7-95fd-42cb16f03aa4.png)

C
![homepage - footer - option 3](https://cloud.githubusercontent.com/assets/1719763/24758415/47264760-1ab0-11e7-9dbd-cf0295a022cf.png)

D
![homepage - footer - option 4](https://cloud.githubusercontent.com/assets/1719763/24758414/4722afb0-1ab0-11e7-9bd3-a5acc14b57a9.png)

E
![homepage - footer - option 5](https://cloud.githubusercontent.com/assets/1719763/24758417/47509fa6-1ab0-11e7-81fd-edfb68157137.png)

F
![homepage - footer - option 6](https://cloud.githubusercontent.com/assets/1719763/24758416/47292c96-1ab0-11e7-8015-158a92d6027a.png)

**Comment by jesseclay** [comment]
I'm not really crazy about any of these options

**Comment by olizilla** [comment]
@jesseclay how about reusing the one from https://ipld.io but without the background image?

<img width="1184" alt="screenshot 2017-06-28 10 24 17" src="https://user-images.githubusercontent.com/58871/27629973-faa30f4a-5beb-11e7-84fc-b3745257ff5b.png">

We can choose a more sensible background colour for this sites palette, or stick with white, but in general I like the layout of the ipld one.
