### ISSUE TITLE
Really like leveldb website and can be a good inspiration from it

### ISSUE THREAD

**Issue by diasdavid** [libp2p/website#4]
http://leveldb.org/

**Comment by diasdavid** [comment]
@kyledrake what you think about the leveldb website? Would love to have something similar to libp2p! :D

**Comment by diasdavid** [comment]
@RichardLitt have you looked at this? Also https://github.com/libp2p/libp2p-website/pull/6, let's try to have a chat today of where to take libp2p.io :)

**Comment by RichardLitt** [comment]
This is pretty. :)

**Comment by VictorBjelkholm** [comment]
List of websites to take inspiration from: https://github.com/libp2p/website/issues/12
