### ISSUE TITLE
Update bundles array for js-ipfs & go-ipfs

### ISSUE THREAD

**Issue by jesseclay** [libp2p/website#43]
Bundles are now populating from the array in the bundes_data.js file. @diasdavid @whyrusleeping mind each going through the file & making sure things look good? If any particular module is 'unstable' (not yet launched), please add it into the empty array with that status so the 'section' is not empty when selected.

Thanks!

**Comment by diasdavid** [comment]
There you go https://github.com/libp2p/website/pull/44

**Comment by jesseclay** [comment]
done in #44 & #45
