### ISSUE TITLE
Decrease cpu usage in animations

### ISSUE THREAD

**Issue by jbenet** [libp2p/website#46]
Right now the animations (particularly the collab hexes) are consuming a ton of CPU. This needs to be reduced. 

I suggest:
- remove the growing/shrinking/floating. (i think this looks really bad, too. so my motivation for killing this is dual). Just fix the grid and scroll the grid to the left all-together. 
- make sure the whole grid (whole div elem, or canvas or whatever) is being moved once, instead of the move left being applied per-hex.

LMK if the above is not clear.

**Comment by jesseclay** [comment]
completed in #47
