### ISSUE TITLE
Analytics: track links clicked

### ISSUE THREAD

**Issue by jesseclay** [libp2p/website#49]
I just implemented basic page-view tracking, but it would be useful to see which external links are clicked from the site: "Try libp2p", "Implementations", "Specification", etc..

**Comment by jesseclay** [comment]
likely will want access to google analytics to verify tracking is working -- if you want access for this ticket just ping me here.

**Comment by diasdavid** [comment]
This should be done now that Hugo is injecting GA everywhere https://github.com/libp2p/website/blob/master/config.toml#L8

**Comment by diasdavid** [comment]
@jesseclay please confirm or share access with me.

**Comment by olizilla** [comment]
I think that change will ensure that page views are tracked, but to get analytic events on people interacting with the bundles tables we'd need to add specific ga event triggers in js.

**Comment by diasdavid** [comment]
Thanks @olizilla. We are good with just tracking page views :)
