### ISSUE TITLE
TLS Cert Expired

### ISSUE THREAD

**Issue by lidel** [libp2p/website#68]
@kenshyx  noted on IRC that it is time for a new one:

![screenshot_12](https://user-images.githubusercontent.com/157609/38134051-db51b840-3411-11e8-82cd-145b5619b3ca.png)

I strongly feel this should be automated somehow, at least for `*.bootstrap.libp2p.io`.
Right now all the bootstrap nodes for js-ipfs seem to have expired certificates :'(

**Comment by VictorBjelkholm** [comment]
Looking into it.

**Comment by lgierth** [comment]
This should be fixed now - sorry about that. I wasn't aware these were still used in js-ipfs and only applied the new certs to `wss0` and `wss1`.
