### ISSUE TITLE
Rust implementation and others are not included

### ISSUE THREAD

**Issue by jamesray1** [libp2p/website#74]

**Comment by mgoelzer** [comment]
Closing after PR #79.  Please reopen if there are other implementations that aren't reflected on the website.

**Comment by ITwrx** [comment]
The nim implementation is not listed. 

https://github.com/status-im/nim-libp2p

it's already being used in a messaging client: https://status.im/

**Comment by DannyS03** [comment]
With some changes previously pushed, implementations page is being updated to the latest as part of https://github.com/libp2p/website/issues/138
