### ISSUE TITLE
pages don't render with latest hugo

### ISSUE THREAD

**Issue by gnunicorn** [libp2p/website#78]
Trying to get the website up and running, I installed latest `hugo` (`Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-02T22:40:09+0200`) and doing make serve, the main-page links to `/implementations`, `/bundles`, etc are broken (give a 404). It looks like hugo is not even rendering them at all.

**Comment by gnunicorn** [comment]
Providing some helper info, the last version that works for me (Arch Linux) is `Hugo Static Site Generator v0.31.1 linux/amd64 BuildDate: 2017-11-27T21:31:31+01:00`, every version after  gives me a 404 for the subpages and doesn't appear to render them.

**Comment by mgoelzer** [comment]
I have the same 404 problem.  I have tried every permutation of macOS and Ubuntu and Chrome and Firefox:  always the same result.  Happens with both Hugo 0.40 and 0.48.

**Comment by DannyS03** [comment]
Believe we can close this based on the stale nature and "edit" update. Please reopen if otherwise
