### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by RichardLitt** [libp2p/website#8]
Things to have on the website: 
- [ ] Status
- [ ] Examples
- [ ] Documentation 
- [ ] Pointers to implementations
- [ ] Tooling
- [ ] Contribute
- [ ] Related

**Comment by RichardLitt** [comment]
# libp2p.io 3.0

Participants: @diasdavid and @RichardLitt

## Next Iteration

### Overall Goals
- Inform the users
  libp2p is the modular network stack
  two major things -> process addressing + runtime freedom
- Bring the spec from libp2p org and bring it to the webpage

### Sections

- [ ] Blurb // communication
- [ ] Spec
exists, not super ready, but there is already a good start
- [ ] Implementations
- js-ipfs, go-ipfs, swift, python, rust (if not in rust, riir). 
- Use a table, like iswebrtcreadyyet

- [ ] Examples
  - I don't think so?
  - We can have some examples that use the thing as a whole (how to create custom libp2p builds will come later)

- [ ] Contribute :+1:
- [ ] Notes and Discussions -- "Learn More" section
- [ ] PubSub
- [ ] Peer Routing & Content Routing
- [ ] Roadmap (with hedging, as this is moving)

### Good to have

- [ ] Navigation Bar
- [ ] Build a libp2p/spec repo: https://github.com/libp2p/spec
- [ ] Pull the commits from the ipfs/spec repo for the libp2p spec, preserving history
- [ ] Change all links
- [ ] Standardize
- [ ] Link on the website
- [ ] Tables
- Modules for various modules (libp2p-tcp, libp2p-swarm, libp2p-spdy, etc) x languages
- color scheme 
- red: not done
- yellow: in progress
- green: done and interops with the other impls
- light green: done and stable

### Examples
- Cbor http://cbor.io/
- ndjson
- http://iswebrtcreadyyet.com/


## Website 4.0 

_Ignore these for now, will be in the next iteration_

- [ ] Tooling
- [ ] Related

**Comment by RichardLitt** [comment]
@diasdavid I need help with the wording for the sections, as I'm still unclear on libp2p and how best to market it and talk about it. I've added some notes to each section, clarifying what I would like help with. I think out best bet would be to walk through it over video and talk about it? Would you be able to do that? 

See the commit, here: https://github.com/libp2p/website/commit/cdbb1717b55b702c9cb3d59442e43111b044ac60

**Comment by RichardLitt** [comment]
@diasdavid Do you have time to help me with this, this week? when are you back in Europe? :)

**Comment by RichardLitt** [comment]
@diasdavid How about today?

**Comment by VictorBjelkholm** [comment]
Closing this in favor of https://github.com/libp2p/website/issues/12 and we'll take a look at this moving forward in the future to make sure we don't miss anything.
