### ISSUE TITLE
site down: new deploys don't seem to resolve via the gateway

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/website#95]
I'm not sure what the cause of this is yet, but recent builds of the website (e.g. from #93) aren't resolving from the gateway, so libp2p.io is currently spinning for a while before eventually returning a 504.

I first thought it was a dnslink issue, since `dig libp2p.io -t TXT` doesn't show a `_dnslink` record:

```

; <<>> DiG 9.10.6 <<>> libp2p.io -t TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7783
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;libp2p.io.			IN	TXT

;; ANSWER SECTION:
libp2p.io.		3599	IN	TXT	"v=spf1 a include:_spf.google.com ~all"

;; Query time: 84 msec
;; SERVER: 192.168.86.1#53(192.168.86.1)
;; WHEN: Thu Jun 20 15:08:48 EDT 2019
;; MSG SIZE  rcvd: 88
```

However, I also can't grab the hash (as reported by the [circle build](https://circleci.com/gh/libp2p/website/106)) - https://ipfs.io/ipfs/QmaYRVyPKpN8FXy9HS1t9Zhtjo4RpYXgiuNj1ins9fiLuW seems to hang forever waiting to resolve.

@olizilla is there anything weird about this site vs other sites that would cause this? the circle setup seems basically the same as for docs.libp2p.io, so idk what might be different.

Oddly, I also can't seem to resolve the *last* version that was published (from #92): 
https://ipfs.io/ipfs/QmbD43XgQ7Tb4242yVZR5kCRUjkonmaZqBWjsfPs5eD9xm/

**Comment by yusefnapora** [comment]
This is looking like it may be a transient gateway performance thing. I manually pinned the site, and it is resolving for me now, but taking forever to actually download.

**Comment by olizilla** [comment]
Yep, there is currently a problem with content discovery speed on the gateway

**Comment by yusefnapora** [comment]
right on, that makes sense, thanks Oli. I think I'll close this issue, since it seems the site deployed after all :)

**Comment by olizilla** [comment]
For future issue spurlunkers, the dnslink txt record gets set on an _dnslink subdomain of the site.

The simplest way to find what the current dnslink for a domain is set to is to ask IPFS...

```console
⨎ ipfs dns libp2p.io
/ipfs/QmaYRVyPKpN8FXy9HS1t9Zhtjo4RpYXgiuNj1ins9fiLuW
```

if you want to double check, you can dig the _dnslink subdomain

```console
$ dig _dnslink.libp2p.io -t TXT +short
"dnslink=/ipfs/QmaYRVyPKpN8FXy9HS1t9Zhtjo4RpYXgiuNj1ins9fiLuW"
```
